HOST = 'http://127.0.0.1'
PORT = 5000
BASE_URL = f'{HOST}:{PORT}'

_ENDPOINT_BASE = '/api/v1.0/'

HEALTCHECK_ENDPOINT = _ENDPOINT_BASE + 'healtcheck'
USERS_ENDPOINT = _ENDPOINT_BASE + 'users'
USER_STATS_ENDPOINT = USERS_ENDPOINT + '/stats'

GAMES_ENDPOINT = _ENDPOINT_BASE + 'games'
